[workspace]
members = [
    "dearbitrary",
    "dearbitrary_derive",
]

[workspace.dependencies]
arbitrary = { version = "1.3.1", features = ["derive"] }
proc-macro2 = "^1.0.38"
quote = "1.0.28"
syn = { version = "2.0.17", features = ['derive'] }

